# Climate, Environment & Pollution
## EDA, Preprocessing & Merge

In [12]:
### Scrape response variables
#from Response_Variable import *
!python Response_Variable.py

In [105]:
import os
import pandas as pd
pd.set_option('display.max_rows', 150)
#pd.options.mode.chained_assignment = None
from eurostat import *
import numpy as np

## Air Quality

In [71]:
dpath = '../../data/'
airqual = pd.read_csv((dpath + 't2020_rn210.tsv'), sep='\t')
airqual.head(1)

,"airpol,geo\time",1992,1993,1994,1995,1996,1997,1998,1999,2000,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
0,"PM10,AT",:,:,:,:,:,:,:,:,25.9,...,23.9,26.9,27.1,22.5,24.6,21.5,20.4,18.3,19.1,21.8

## Emissions

In [72]:
emissions = pd.read_csv((dpath + 't2020_30.tsv'), sep='\t')
emissions.head(1)

,"indic_eu,geo\time",1990,1991,1992,1993,1994,1995,1996,1997,1998,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,TARGET
0,"T2020_30,AT",100,104.75,96.5,96.9,97.26,101.68,105.92,105.45,104.68,...,109.19,106.41,102.82,103.25,98.68,101.6,103.05,106.17,102.66,:

## Renewables

In [73]:
renew = pd.read_csv((dpath + 't2020_31.tsv'), sep='\t')
renew.head(1)

,"unit,indic_eu,geo\time",2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,TARGET
0,"PC,T2020_31,AL",29.621,31.367,32.070,32.657,32.448,31.437,31.867,31.187,35.152,33.167,31.476,34.387,35.487,34.465,34.865,:

## Eurostat Library

In [77]:
#toc_df = get_toc_df()
subset_toc_df(toc_df, 'city').loc[:,('code','title')]

                   code                                              title
320        reg_tour_cap  Capacity of collective tourist accommodation: ...
718                 urb                                    City statistics
835             med_rd4           Road equipment: load capacity of lorries
841             med_ra3  Rail equipment: number and capacity of railway...
842             med_ra4  Rail equipment: number and load capacity of go...
852             med_ma4  Maritime equipment - carrying capacity of ship...
853             med_ma5  Maritime equipment - carrying capacity of ship...
4732      crim_pris_cap         Prison capacity and number of persons held
4838       sbs_na_2a_el  Annual detailed enterprise statistics on elect...
4852     sbs_sc_2d_el95  Electricity, gas and water by employment size ...
4853     sbs_sc_2d_el02  Electricity, gas and water by employment size ...
5169           tour_cap   Capacity of tourist accommodation establishments
5963     rail_eq_pa_cty  Capacity of passenger railway vehicles, by typ...
5964     rail_eq_pa_csb  Capacity of passenger railway vehicles, by cat...
5967    rail_eq_wagon_c                            Load capacity of wagons
6141  road_eqs_lormot_h  Lorries, by type of motor energy and load capa...
6142  road_eqs_lornum_h                          Lorries, by load capacity
6146  road_eqs_lorton_h                          Lorries, by load capacity
6147    road_eqs_semitn                    Semi-trailers, by load capacity
6149    road_eqs_trailn                         Trailers, by load capacity
6158    road_eqr_bussea  New registrations of motor coaches, buses and ...
6170  road_eqr_lorrin_h     New registrations of lorries, by load capacity
6171  road_eqr_lormot_h  New registrations of lorries, by motor energy ...
6172    road_eqr_loralt  New registrations of lorries, by alternative m...
6174  road_eqr_lorrit_h     New registrations of lorries, by load capacity
6175     road_eqr_lsttt  New registrations of lorries, semi-trailers an...
6176    road_eqr_semitn  New registrations of semi-trailers, by load ca...
6177    road_eqr_trailn    New registrations of trailers, by load capacity
6211      road_go_ta_lc  Annual road freight transport, by load capacit...
6259     iww_eq_loadcap  Self-propelled vessels, dumb and pushed vessel...
6260    iww_eq_power_lo   Power of self-propelled vessels by load capacity
6263     iww_eq_age_loa  Load capacity of self-propelled vessels, by da...
6266       iww_ec_ent_c  Carrying capacity of the inland waterways tran...
6299      pipe_if_capac            Carrying capacity of pipelines operated
6649         env_wasfac  Number and capacity of recovery and disposal f...
6694        nrg_bal_peh  Production of electricity and derived heat by ...
6701           nrg_cb_e  Supply, transformation and consumption of elec...
6710       nrg_ind_ured        Use of renewables for electricity - details
6716        nrg_ind_peh  Gross and net production of electricity and de...
6717      nrg_ind_pehcf  Gross production of electricity and derived he...
6718      nrg_ind_pehnf  Gross production of electricity and derived he...
6719      nrg_ind_pehap  Production of electricity and heat by autoprod...
6727        nrg_inf_epc  Electricity production capacities by main fuel...
6728      nrg_inf_epcrw  Electricity production capacities for renewabl...
6729       nrg_inf_epct  Electricity production capacities for combusti...
6743          nrg_ti_eh  Imports of electricity and derived heat by par...
6749          nrg_te_eh  Exports of electricity and derived heat by par...
6756          nrg_cb_em  Supply, transformation and consumption of elec...
6757         nrg_cb_eim           Electricity available to internal market
6758         nrg_cb_pem  Net electricity generation by type of fuel - m...
6776           nrg_125m               Imports - electricity - monthly data
6779           nrg_135m               Exports - electricity - monthly data
6783       nrg_ind_342m       Supply electricity - short term monthly data
6789           nrg_105m               Supply of electricity - monthly data
6800          nrg_price  Energy statistics - prices of natural gas and ...
6801             nrg_pc  Energy statistics - natural gas and electricit...
6804         nrg_pc_204  Electricity prices for household consumers - b...
6805         nrg_pc_205  Electricity prices for non-household consumers...
6808       nrg_pc_204_c  Electricity prices components for household co...
6809       nrg_pc_205_c  Electricity prices components for non-househol...
6810         nrg_pc_206  Share for transmission and distribution in the...
6811           nrg_pc_h  Energy statistics - natural gas and electricit...
6814       nrg_pc_204_h  Electricity prices for domestic consumers - bi...
6815       nrg_pc_205_h  Electricity prices for industrial consumers - ...
6816       nrg_pc_206_h  Electricity - marker prices - bi-annual data (...
6817         nrg_market  Energy statistics - market structure indicator...
6818       nrg_ind_331a  Market share of the largest generator in the e...
7957         t_tour_cap   Capacity of tourist accommodation establishments
8222           ten00117                 Electricity prices by type of user
8224           ten00119  Market share of the largest generator in the e...
8538           teibs070  Current level of capacity utilization in manuf...
9338            mii_urb                                    City statistics
9774        nrg_bal_peh  Production of electricity and derived heat by ...
9775        nrg_inf_epc  Electricity production capacities by main fuel...
9819      nrg_inf_epcrw  Electricity production capacities for renewabl...

## Climate/Env Canditates from Eurostat
Environment - cities and greater cities 	urb_cenv


Energy infrastructure and capacities 	nrg_inf
    Electricity production capacities for renewabl... 	nrg_inf_epcrw

sdg_11 -> Goal 11 - Sustainable cities and communities 

envir 	Environment and energy
env 	Environment
qol_env 	Natural and living environment

### othews
Culture and tourism - cities and greater cities 	urb_ctour
Education - cities and greater cities 	urb_ceduc 	


#eurostat.get_dic(code)
https://ec.europa.eu/eurostat/web/sdmx-web-services/sdmx

In [43]:
cities_dict = get_dic('cities')

In [158]:

urb_cenv = get_data_df('urb_cenv', flags=False)
urb_cenv.head()

,indic_ur,cities\time,2019,2018,2017,2016,2015,2014,2013,2012,...,1999,1998,1997,1996,1995,1994,1993,1992,1991,1990
0,EN1002V,BE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.40,3.60,4.7,4.3,4.5,4.2,3.9,4.1,4.6,NaN
1,EN1002V,CY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,9.1,NaN,NaN,NaN,NaN,NaN,NaN
2,EN1002V,CZ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN
3,EN1002V,ES,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7.26,7.41,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,EN1002V,HU,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
Cities_with_codes = pd.read_csv("./Cities_with_codes.csv", index_col=0)
CityDI = Cities_with_codes.iloc[:,0].to_dict()

In [162]:
sub = urb_cenv[urb_cenv.loc[:,"cities\\time"].isin(CityDI.values())].iloc[400:800, 2:10]

sub.dropna(axis=0, thresh=1)#how='all')

#urb_cenv.iloc[:,1]

#urb_cenv = urb_cenv[(urb_cenv.ArticleChannel == "Inland") & (~df.ArticleRessortName.isin([ "Pensionen", "Eurofighter","Off-Topic"]))]

,indic_ur,cities\time,2019,2018,2017,2016,2015,2014,2013,2012,...,1999,1998,1997,1996,1995,1994,1993,1992,1991,1990
132,EN3003V,DE003L1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,159977000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
355,EN3011V,DE003L1,NaN,NaN,NaN,100.0,NaN,100.0,100.0,100.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
599,EN4008V,DE003L1,NaN,1213.82,NaN,NaN,NaN,NaN,1172.8,1186.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [83]:
avail_sdmx_df = get_avail_sdmx_df()
subset_avail_sdmx_df(avail_sdmx_df, 'city')

                                                                name
dataflow
crim_pris_cap             Prison capacity and number of persons held
env_wasfac         Number and capacity of recovery and disposal f...
iww_ec_ent_c       Carrying capacity of the inland waterways tran...
iww_eq_age_loa     Load capacity of self-propelled vessels, by da...
iww_eq_loadcap     Self-propelled vessels, dumb and pushed vessel...
iww_eq_power_lo     Power of self-propelled vessels by load capacity
med_ma4            Maritime equipment - carrying capacity of ship...
med_ma5            Maritime equipment - carrying capacity of ship...
med_ra3            Rail equipment: number and capacity of railway...
med_ra4            Rail equipment: number and load capacity of go...
med_rd4                     Road equipment: load capacity of lorries
nrg_105m                        Supply of electricity - monthly data
nrg_125m                        Imports - electricity - monthly data
nrg_135m                        Exports - electricity - monthly data
nrg_bal_peh        Production of electricity and derived heat by ...
nrg_cb_e           Supply, transformation and consumption of elec...
nrg_cb_eim                  Electricity available to internal market
nrg_cb_em          Supply, transformation and consumption of elec...
nrg_cb_pem         Net electricity generation by type of fuel - m...
nrg_ind_331a       Market share of the largest generator in the e...
nrg_ind_342m            Supply electricity - short term monthly data
nrg_ind_peh        Gross and net production of electricity and de...
nrg_ind_pehap      Production of electricity and heat by autoprod...
nrg_ind_pehcf      Gross production of electricity and derived he...
nrg_ind_pehnf      Gross production of electricity and derived he...
nrg_ind_ured             Use of renewables for electricity - details
nrg_inf_epc        Electricity production capacities by main fuel...
nrg_inf_epcrw      Electricity production capacities for renewabl...
nrg_inf_epct       Electricity production capacities for combusti...
nrg_pc_204         Electricity prices for household consumers - b...
nrg_pc_204_c       Electricity prices components for household co...
nrg_pc_204_h       Electricity prices for domestic consumers - bi...
nrg_pc_205         Electricity prices for non-household consumers...
nrg_pc_205_c       Electricity prices components for non-househol...
nrg_pc_205_h       Electricity prices for industrial consumers - ...
nrg_pc_206         Share for transmission and distribution in the...
nrg_pc_206_h       Electricity - marker prices - bi-annual data (...
nrg_te_eh          Exports of electricity and derived heat by par...
nrg_ti_eh          Imports of electricity and derived heat by par...
pipe_if_capac                Carrying capacity of pipelines operated
rail_eq_pa_csb     Capacity of passenger railway vehicles, by cat...
rail_eq_pa_cty     Capacity of passenger railway vehicles, by typ...
rail_eq_wagon_c                              Load capacity of wagons
road_eqr_bussea    New registrations of motor coaches, buses and ...
road_eqr_loralt    New registrations of lorries, by alternative m...
road_eqr_lormot_h  New registrations of lorries, by motor energy ...
road_eqr_lorrin_h     New registrations of lorries, by load capacity
road_eqr_lorrit_h     New registrations of lorries, by load capacity
road_eqr_lsttt     New registrations of lorries, semi-trailers an...
road_eqr_semitn    New registrations of semi-trailers, by load ca...
road_eqr_trailn      New registrations of trailers, by load capacity
road_eqs_lormot_h  Lorries, by type of motor energy and load capa...
road_eqs_lornum_h                          Lorries, by load capacity
road_eqs_lorton_h                          Lorries, by load capacity
road_eqs_semitn                      Semi-trailers, by load capacity
road_eqs_trailn                           Trailers, by load capacity
road_go_ta_lc      Annual road freight transport, by load capacit...
sbs_na_2a_el       Annual detailed enterprise statistics on elect...
sbs_sc_2d_el02     Electricity, gas and water by employment size ...
sbs_sc_2d_el95     Electricity, gas and water by employment size ...
teibs070           Current level of capacity utilization in manuf...
ten00117                          Electricity prices by type of user
ten00119           Market share of the largest generator in the e...

In [ ]:
code = 'nrg_ind_ured'
filter_pars = {}
#filter_pars = {'FREQ': ['A',], 'PRCCODE': ['08111250','08111150']}
sdmxdf = get_sdmx_data_df(code, 2012, 2019, filter_pars, flags=False, verbose=True)

In [89]:
sdmxdf

,SIEC,UNIT,NRG_BAL,GEO,FREQ,2018,2017,2016,2015,2014,2013,2012
0,E7000,GWH,GEP_NPUMP_MIX,AL,A,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,E7000,GWH,GEP_NPUMP_MIX,AT,A,3574.539,2958.855,3877.193,3748.451,4375.092,4403.564,4626.926
2,E7000,GWH,GEP_NPUMP_MIX,BA,A,336.0,81.0,111.0,242.0,173.0,713.0,239.0
3,E7000,GWH,GEP_NPUMP_MIX,BE,A,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,E7000,GWH,GEP_NPUMP_MIX,BG,A,717.301,244.947,444.0,391.0,335.0,296.0,261.0
...,...,...,...,...,...,...,...,...,...,...,...,...
3595,W6210,GWH,NMLPRD_PURE,SI,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3596,W6210,GWH,NMLPRD_PURE,SK,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3597,W6210,GWH,NMLPRD_PURE,TR,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3598,W6210,GWH,NMLPRD_PURE,UK,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3599,W6210,GWH,NMLPRD_PURE,XK,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN